name: Update README Daily

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      - name: Run update script
        run: python .github/scripts/update_readme.py

      - name: Commit changes
        run: |
          git config --global user.name douglasliao77
          git config --global user.email douglasliao77@gmail.com
          git add README.md
          git commit -m 'Daily update to README'
          git push
        continue-on-error: true  # Prevents error if there's no change to commit