name: Update README Daily

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print environment variables
        run: printenv

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz
          pip install python-dotenv

      - name: Run update script
        run: python3 .github/scripts/update_readme.py

      - name: Commit changes
        run: |
          git config --global user.name douglasliao77
          git config --global user.email douglasliao77@gmail.com
          git add README.md
          git status
          git commit -m 'Daily update to README'
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/douglasliao77/douglasliao77.git
        continue-on-error: true  # Prevents error if there's no change to commit
        
      - name: Run script using secrets
        run: |
          echo "Using API_KEY=${{ secrets.API_KEY }}"
          python script.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
